name: Moury Bot 24 Jam
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'
concurrency:
  group: moury-bot
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
